### ISSUE TITLE
Pre and post publish checklist

### ISSUE THREAD

**Issue by bph** [WordPress/developer-blog-content#19]
### Pre-publishing checklist: (updated 1/29/2024)

- [ ] Post Title and subheaders in sentence case
- [ ] Are Category or Categories selected?
- [ ] Are Tags identifies?
- [ ] Is there an explicit Excerpt?
- [ ] Are all images files uploaded to the media library
- [ ] Do all images have an alt-text?
- [ ] For TOC us the Pattern under _Developer Blog > Table of contents_
- [ ] Assign or upload a featured image
- [ ] Props added? (See [Guidelines](https://make.wordpress.org/core/handbook/best-practices/post-comment-guidelines/#giving-proper-credit-props))
- [ ] add **copy for a social post** as comment to this issue ([example](https://github.com/WordPress/developer-blog-content/issues/152#issuecomment-1654259045))
🙌 Publish! 📗

### Post-publishing checklist
- [ ] add Props for reviews to #props channel in WP Slack ([Example](https://wordpress.slack.com/archives/C0FRG66LR/p1689098122307029)) (use Slack handles) 
- [ ] Add the label "post to social" to the issue
- [ ] close the issue with a comment to link to the published post
- [ ] close the accompanying discussion with the link to the published post.

**Comment by ryanwelcher** [comment]
@bph would it be helpful to have a plugin in place for something like this? I have a plugin that can be modified for this if you'd like.

**Comment by bph** [comment]
Thanks @ryanwelcher - That would be great. I am just not sure how easy it is to add 3rd party plugins to a .org network.  Before we do that we need to have the checklist complete. 

When I create this issue, I was more looking at the a GitHub Action to add this checklist to an issue when it made it into 2nd review column so when all checks are done, they can forward to "Ready to be Published". 
Could you help with that, too? I haven't done anything with GitHub Actions + projects yet, but I know that it's possible :-)

**Comment by ryanwelcher** [comment]
> When I create this issue, I was more looking at the a GitHub Action to add this checklist to an issue when it made it into 2nd review column so when all checks are done, they can forward to "Ready to be Published". Could you help with that, too? I haven't done anything with GitHub Actions + projects yet, but I know that it's possible :-)

Sure I can have a look, just need to understand the flow we're looking for.

**Comment by DaisyOlsen** [comment]
I use the GitHub saved reply option for inserting checklists into issues, but an Issue template could also work since it's all within a single Repo. I'm not sure about the automation for the Project, there are some automations there, but it's pretty limited.

**Comment by bph** [comment]
Need 
- How to do props page
- How to change template to Center column (video) http://recordit.co/ItqX1TVHMS
- Table of Contents formatting 
<img width="1071" alt="Screenshot 2023-06-20 at 11 38 21" src="https://github.com/WordPress/developer-blog-content/assets/39980/ca292641-6003-4948-aa5a-8759bc92b404">

**Comment by bph** [comment]
This issues can be closed, now that Pre- and post publish check list are added automatically to issues labeled "flow-ready to publish" 
[See also this wiki page. ](https://github.com/WordPress/developer-blog-content/wiki/Pre-and-post-publishing-checklist)
