### ISSUE TITLE
Dev Blog Documentation Issues Tracking

### ISSUE THREAD

**Issue by bph** [WordPress/developer-blog-content#221]
Over the last 12 months, we made a few modification to the processes of the **idea to publish** workflow as well as updates to the site admin and meeting facilitation, including the way we publish and update documentation. The information is a bit fragmented for now. This tracking issue is the source of truth of identified tasks. 

**It's a Work in Progress [WIP]**

The envisioned workflow for this project: 

- Create checklist items, 
- organize the list into chapter heading, 
- then we create issues with the label 'Dev Blog Docs'. 
- assigned or self-assigned issues to collaborator. 

The documentation will be [published in this repo's Wiki](https://github.com/WordPress/developer-blog-content/wiki).
--
## Meeting Facilitation

- [ ] Agenda Discussion
- [ ] google Doc roll over from last months
- [ ] Agenda announcement w/ latest topic discussions
- [ ] Voting process 
- [ ] Summary post (posting guidelines) 
- [ ] How to request  /here privileges for Facilitator
- [ ] How to request admin access to make core blog for summary post. 
- [ ] Process Approved Discussions to issues.  

## Idea to published article journey

- [ ] How to write a good pitch + Template. (https://github.com/WordPress/developer-blog-content/issues/69)
- [ ] Project Kanban board. ([updates to this earlier version](https://developer.wordpress.org/news/how-to-contribute/))
- [ ] Writing Guidelines ([do we need to update this page?](https://developer.wordpress.org/news/tips-and-guidelines-for-writers/) )
- [ ] #242
- [ ] #241
- [ ] Pre-publish check list (see #19)
- [ ] Post-publish check-list (see #19)
- [ ] How to do props?
- [ ] ##131

_Tobe continued_
